# Generated by Django 4.0.1 on 2022-01-31 10:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fid', models.IntegerField(null=True)),
                ('date', models.CharField(max_length=15, null=True)),
                ('description', models.CharField(max_length=100, null=True)),
                ('domains', models.CharField(max_length=200, null=True)),
                ('form_url', models.CharField(max_length=100, null=True)),
                ('form_status', models.BooleanField()),
                ('uid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
