# Generated by Django 4.0.1 on 2022-01-31 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form',
            name='form_url',
        ),
    ]
