# Generated by Django 4.0.1 on 2022-01-31 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_remove_form_form_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='fid',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
