# Generated by Django 4.0.1 on 2022-01-31 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0004_trainee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainee',
            name='id',
        ),
        migrations.AlterField(
            model_name='trainee',
            name='trainee_email',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
