# Generated by Django 4.0.1 on 2022-02-03 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0004_trainee'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainee',
            name='trainee_resume',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
