# Generated by Django 4.0.1 on 2022-03-13 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0006_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainee',
            name='trainee_score',
            field=models.IntegerField(null=True),
        ),
    ]
