# Generated by Django 4.0.1 on 2022-04-02 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0007_trainee_trainee_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='fee_amount',
            field=models.IntegerField(null=True),
        ),
    ]
