# Generated by Django 4.0.1 on 2022-04-03 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0008_form_fee_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainee',
            name='trainee_paymentId',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='trainee',
            name='trainee_paymentStatus',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
